name = input('Enter Your name : ')

print('\n', name, end=' ')
a = float(input('Enter a Number : '))

print('\nMultiplication Table for ', a)
print()
print(f'    1.0  * {a} = {1 * a}    ')
print(f'    2.0  * {a} = {2 * a}    ')
print(f'    3.0  * {a} = {3 * a}    ')
print(f'    4.0  * {a} = {4 * a}    ')
print(f'    5.0  * {a} = {5 * a}    ')
print(f'    6.0  * {a} = {6 * a}    ')
print(f'    7.0  * {a} = {7 * a}    ')
print(f'    8.0  * {a} = {8 * a}    ')
print(f'    9.0  * {a} = {9 * a}    ')
print(f'    10.0 * {a} = {10 * a}    ')
print()

print('Exponent Table for ', a)
print()
print(f'    {a} ^ 1  = {a ** 1}    ')
print(f'    {a} ^ 2  = {a ** 2}    ')
print(f'    {a} ^ 3  = {a ** 3}    ')
print(f'    {a} ^ 4  = {a ** 4}    ')
print(f'    {a} ^ 5  = {a ** 5}    ')
print(f'    {a} ^ 6  = {a ** 6}    ')
print(f'    {a} ^ 7  = {a ** 7}    ')
print(f'    {a} ^ 8  = {a ** 8}    ')
print(f'    {a} ^ 9  = {a ** 9}    ')
print(f'    {a} ^ 10 = {a ** 10}    ')
print()
